version: '3.9'
networks:
  basic:
services:
  front:
    container_name: httpd
    image: httpd
    ports:
      - '8080:80'
    volumes:
      - ./templates/dist/spa/:/usr/local/apache2/htdocs/
    networks:
      - basic
  backend:
    container_name: greaterwms_backend
    image: greaterwms/greaterwms_backend:latest
    volumes:
      - ./:/GreaterWMS/:rw #将前目录挂载到容器下
    ports:
      - '8008:8008'
    command:
      - /bin/bash
      - -c
      - |
        bash backend_start.sh
    networks:
      - basic
  database:
    image: mysql
    container_name: greaterwms-mysql
    #使用该参数，container内的root拥有真正的root权限，否则，container内的root只是外部的一个普通用户权限
    #设置为true，不然数据卷可能挂载不了，启动不起
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "greaterwms"
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "./docker/mysql/data:/var/lib/mysql"
      #根据宿主机下的配置文件创建容器
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/logs:/logs"
    networks:
      - basic
  nginx:
    image: nginx
    container_name: greaterwms_nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      #- 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_new/:/GreaterWMS/static_new:ro
    networks:
      - basic
